#!/usr/bin/env python3
"""
gen_ksweep.py -- tables/ksweep.tex, the selection rule's held-out performance.

The k-sweep exists only as a figure (f10_selection). A referee checking the numbers
wants them as digits, with the intervals, so this emits the table beside it.

Every value is read from the experiment record, never transcribed:
  experiments/w_final/W9_selection/RESULT_ksweep.json
which holds k_sweep (mean regret and per cent optimal, under leave-one-out and under a
whole-topology holdout) and bootstrap_ci (B=2000, resampling the 39 instances).

The generator refuses to write if the record disagrees with the two facts the paper
states about this rule -- that k=5 is identical to k=4, and that the portfolio beats the
best single algorithm -- so the table cannot quietly drift from the prose.
"""
import argparse
import datetime
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PAPER = os.path.dirname(HERE)


def _root():
    return os.environ.get("SPRS_ROOT") or os.path.abspath(os.path.join(PAPER, ".."))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(PAPER, "tables"))
    a = ap.parse_args()

    rec = os.path.join(_root(), "experiments", "w_final", "W9_selection",
                       "RESULT_ksweep.json")
    if not os.path.exists(rec):
        sys.exit(f"gen_ksweep.py: required input missing: {rec}")
    d = json.load(open(rec))
    sweep, ci = d["k_sweep"], d["bootstrap_ci"]

    ks = sorted(sweep, key=lambda x: int(x))
    g = lambda k, f: sweep[k][f]

    # --- self-validation: refuse to emit if the record contradicts the prose ---
    if not (abs(g("4", "loo_mean") - g("5", "loo_mean")) < 1e-9
            and abs(g("4", "topo_mean") - g("5", "topo_mean")) < 1e-9):
        sys.exit("gen_ksweep.py: k=5 is no longer identical to k=4; the paper says it is")
    if not g("4", "loo_mean") < g("1", "loo_mean"):
        sys.exit("gen_ksweep.py: the k=4 portfolio no longer beats the single best algorithm")

    def cell(k, proto):
        key = f"k{k}_{'LOO' if proto == 'loo' else 'unseen-topology'}"
        if key in ci:
            c = ci[key]
            return f"{c['mean']:.4f} & [{c['lo']:.4f}, {c['hi']:.4f}]"
        return f"{g(k, proto + '_mean'):.4f} & ---"

    L = [
        "% GENERATED by scripts/gen_ksweep.py -- do not edit by hand.",
        f"% source : experiments/w_final/W9_selection/RESULT_ksweep.json",
        f"% date   : {datetime.date.today().isoformat()}",
        "% Intervals are 95% bootstrap CIs, B=2000, resampling the 39 instances.",
        r"\begin{tabular}{@{}c rr rr r@{}}",
        r"\toprule",
        r"& \multicolumn{2}{c}{leave-one-out} & \multicolumn{2}{c}{unseen topology}"
        r" & \\",
        r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}",
        r"$k$ & mean & 95\% CI & mean & 95\% CI & \% optimal \\",
        r"\midrule",
    ]
    for k in ks:
        if int(k) > 8:
            continue
        mark = r"\textbf{" if k == "4" else "{"
        L.append(f"{mark}{k}}} & {cell(k,'loo')} & {cell(k,'topo')} & "
                 f"{g(k,'topo_pct_opt'):.1f}\\% \\\\")
    L += [
        r"\bottomrule",
        r"\end{tabular}",
    ]

    os.makedirs(a.out, exist_ok=True)
    path = os.path.join(a.out, "ksweep.tex")
    with open(path, "w") as fh:
        fh.write("\n".join(L) + "\n")
    print(f"wrote {path} ({len([k for k in ks if int(k) <= 8])} rows; "
          f"k=4 held-out {g('4','topo_mean'):.4f}, k=5 identical as the paper states)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
