#!/usr/bin/env python3
"""
gen_showcase.py -- build the showcase edition from main.tex.

The submission is IEEEtran: two columns, Times, 8.9cm measure. That format is a
constraint, not a design. This produces a second rendering of the SAME content in a
single generous column with real typography, for reading and for showing people.

One source of truth: the body is extracted from main.tex, so the showcase cannot drift
from the submission. Only IEEEtran-specific markup is neutralised; nothing is rewritten.

Builds with pdflatex. Usage: python3 scripts/gen_showcase.py && pdflatex showcase
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PAPER = os.path.dirname(HERE)

PREAMBLE = r"""% GENERATED by scripts/gen_showcase.py -- do not edit by hand.
% The showcase edition: same content as main.tex, set for reading rather than for
% IEEE's two-column grid. Build with lualatex.
\documentclass[11pt]{article}

% Typography note: this machine's lualatex/fontspec cannot resolve any system font
% -- luaotfload has no font database and luaotfload-tool is not installed, so even
% the default Latin Modern OTF fails to load. So this builds with pdflatex on
% TeX-native faces instead, which is more portable anyway.
%
% Bitstream Charter (Matthew Carter, 1987) for text: designed for low-resolution
% output, so it holds up in print and on screen, with a large x-height and sturdy
% serifs that suit dense technical prose. TeX Gyre Heros for labels and headings.
\usepackage[T1]{fontenc}
\usepackage{charter}
\usepackage{tgheros}
\renewcommand{\ttdefault}{cmtt}

\usepackage[a4paper,inner=30mm,outer=50mm,top=26mm,bottom=28mm,
            marginparwidth=32mm,marginparsep=6mm]{geometry}
\usepackage{microtype}
\usepackage{amsmath,amssymb,amsthm}
\usepackage{mathtools}
\usepackage{graphicx}
\usepackage{tikz}
\usetikzlibrary{positioning,shapes.geometric,shapes.multipart,arrows.meta,%
                calc,fit,backgrounds,patterns,decorations.pathreplacing,chains,scopes}
\usepackage{pgfplots}
\pgfplotsset{compat=1.18}
\usepackage{booktabs}
\usepackage{multirow}
\usepackage{array}
\usepackage{tabularx}
\usepackage{enumitem}
\usepackage{colortbl}
\usepackage{xcolor}
\input{figures/_palette.tex}
\usepackage{titlesec}
\usepackage{caption}
\usepackage{marginnote}
\usepackage[hidelinks]{hyperref}
\usepackage{cite}

\linespread{1.16}
\setlength{\parindent}{0pt}
\setlength{\parskip}{0.62\baselineskip}
\newcolumntype{L}[1]{>{\raggedright\arraybackslash}p{#1}}
\newcolumntype{R}[1]{>{\raggedleft\arraybackslash}p{#1}}
\newcolumntype{C}[1]{>{\centering\arraybackslash}p{#1}}

% ---------------------------------------------------------------- headings
% Sans, tight, with a hairline rule carrying the section number out into the margin.
\titleformat{\section}[hang]
  {\normalfont\sffamily\bfseries\large\color{spInk}}
  {\makebox[0pt][r]{\color{spBlue}\thesection\hspace{6mm}}}{0pt}{}
  [\vspace{-0.55\baselineskip}{\color{spBlue!35}\rule{\linewidth}{0.4pt}}]
\titleformat{\subsection}[hang]
  {\normalfont\sffamily\bfseries\normalsize\color{spInk}}
  {\makebox[0pt][r]{\color{spMute}\thesubsection\hspace{6mm}}}{0pt}{}
\titlespacing*{\section}{0pt}{1.9\baselineskip}{0.7\baselineskip}
\titlespacing*{\subsection}{0pt}{1.15\baselineskip}{0.35\baselineskip}

\captionsetup{font={sf,small},labelfont={bf,color=spBlue},
              labelsep=period,justification=raggedright,singlelinecheck=false,
              skip=7pt}

\theoremstyle{definition}
\newtheorem{definition}{Definition}
\newtheorem{claim}{Claim}
\newtheorem{property}{Property}
\newtheorem{proposition}{Proposition}
\newtheorem{remark}{Remark}
\newtheorem{theorem}{Theorem}
\newtheorem{lemma}{Lemma}

MACROS_PLACEHOLDER

% IEEEtran compatibility: neutralise what the two-column class provides.
\newcommand{\IEEEPARstart}[2]{\textbf{#1}#2}
\providecommand{\IEEEraisesectionheading}[1]{#1}
\newenvironment{IEEEkeywords}{\vspace{0.6\baselineskip}\small\sffamily\noindent
  \textcolor{spBlue}{\textbf{Index terms}}\quad}{\par}
\newcommand{\IEEEpubidadjcol}{}
\providecommand{\balance}{}

\begin{document}
"""

TITLE = r"""
\begin{titlepage}
\thispagestyle{empty}
\vspace*{0.14\textheight}
{\sffamily\fontsize{9}{11}\selectfont\color{spMute}%
 SHOWCASE EDITION \quad\textbullet\quad same content as the IEEE submission\par}
\vspace{5mm}
% \hyphenpenalty and \raggedright together stop the display size from hyphenating
% "Reduction" across a line -- the explicit \\ is the only break wanted here.
{\fontsize{29}{34}\selectfont\color{spInk}\raggedright\hyphenpenalty=10000
 \exhyphenpenalty=10000
 Bitwise-Reproducible Reduction\\[1mm]Across Cluster Reshape\par}
\vspace{4mm}
{\fontsize{15.5}{19}\selectfont\itshape\color{spBlue}A Compiler/Fabric ABI\par}
\vspace{10mm}
{\color{spBlue!35}\rule{58mm}{0.6pt}\par}
\vspace{8mm}
\begin{minipage}{0.78\linewidth}
\setlength{\parskip}{0.5\baselineskip}
{\itshape\color{spMute}\fontsize{11.5}{16}\selectfont
Floating-point addition is not associative, so reducing the same bytes on a
differently-shaped cluster returns a different answer. This paper fixes one
reduction order as an interface contract: the compiler proves it emits that order,
and the fabric refuses to execute anything else.\par}
\end{minipage}
\vfill
{\sffamily\footnotesize\color{spMute}%
 Set in Bitstream Charter and TeX Gyre Heros. Figures drawn in TikZ from the
 same sources the submission typesets.\par}
\end{titlepage}
"""


def main():
    src = os.path.join(PAPER, 'main.tex')
    body = open(src, encoding='utf-8').read()

    # Carry over every macro definition and \input from main.tex's preamble. Doing
    # this dynamically rather than by hand means a macro added to the submission
    # cannot silently expand to nothing in the showcase.
    pre = body[:body.index(r'\begin{document}')]
    keep = []
    for ln in pre.splitlines():
        t = ln.strip()
        if t.startswith('%') or not t:
            continue
        # \newtheorem / \theoremstyle are deliberately NOT carried: the showcase
        # preamble declares its own, and redeclaring them errors with
        # "Command \theorem already defined".
        # IEEEkeywords is excluded because the showcase preamble redefines it for a
        # single-column setting; carrying main.tex's would clash.
        if re.match(r'\\newenvironment\{IEEEkeywords\}', t):
            continue
        if re.match(r'\\(new|renew|provide)command|\\DeclareMathOperator|'
                    r'\\newenvironment|\\newlist|\\setlist|\\input\{data/', t):
            keep.append(ln)
    macros = ('% Macro definitions and generated-data inputs carried over verbatim from\n'
              '% main.tex\'s preamble, so every number in the body expands identically.\n'
              + '\n'.join(keep))

    m = re.search(r'\\begin\{document\}(.*)\\end\{document\}', body, re.S)
    if not m:
        sys.exit('gen_showcase.py: could not find the document body in main.tex')
    b = m.group(1)

    # Drop IEEEtran front matter; the showcase supplies its own title page.
    b = re.sub(r'\\maketitle', '', b)
    b = re.sub(r'\\title\{.*?\n\}', '', b, flags=re.S)
    b = re.sub(r'\\author\{.*?\n\}', '', b, flags=re.S)
    b = re.sub(r'\\markboth\{[^}]*\}\{[^}]*\}', '', b)
    b = re.sub(r'\\IEEEtitleabstractindextext\{', r'{', b)
    b = re.sub(r'\\IEEEdisplaynontitleabstractindextext', '', b)
    b = re.sub(r'\\IEEEpeerreviewmaketitle', '', b)
    b = re.sub(r'\\IEEEpubidadjcol', '', b)
    # figure* / table* have no meaning in one column.
    b = b.replace(r'\begin{figure*}', r'\begin{figure}').replace(r'\end{figure*}', r'\end{figure}')
    b = b.replace(r'\begin{table*}', r'\begin{table}').replace(r'\end{table*}', r'\end{table}')
    # The abstract becomes a lead paragraph rather than a boxed IEEE abstract.
    b = re.sub(r'\\begin\{abstract\}',
               r'\\vspace{2mm}\\begingroup\\sffamily\\small\\color{spInk}'
               r'\\textcolor{spBlue}{\\textbf{Abstract}}\\par\\vspace{1mm}', b)
    b = re.sub(r'\\end\{abstract\}', r'\\endgroup\\vspace{3mm}', b)

    out = PREAMBLE.replace('MACROS_PLACEHOLDER', macros) + TITLE + b + '\n\\end{document}\n'
    dst = os.path.join(PAPER, 'showcase.tex')
    with open(dst, 'w', encoding='utf-8') as fh:
        fh.write(out)
    print(f"wrote {dst} ({len(out.splitlines())} lines) -- build with: pdflatex showcase")
    return 0


if __name__ == '__main__':
    sys.exit(main())
