#!/usr/bin/env python3
r"""
gen_catalogue.py -- emit tables/catalogue.tex.

Replaces the withdrawn winner-share catalogue (T15: winner shares are an
artifact of CSV arrival order) with tie-invariant champion-class membership,
taken verbatim from SELECTION_RULE.json's s2_membership_rates.algorithm.
Row order is by family, never by membership, so the table implies no ranking
among algorithms the council found statistically indistinguishable.
"""
import json, os, sys

# Council record directory.  Resolution order:
#   1. $SPRS_COUNCIL                   -- explicit override
#   2. <paper>/data/council            -- the released artifact layout (the JSONs
#                                         these generators read are vendored there
#                                         so a fresh clone can run them)
#   3. the author's original absolute path, last resort.
def _council_default():
    here = os.path.dirname(os.path.abspath(__file__))
    cand = os.path.join(os.path.dirname(here), "data", "council")
    return cand if os.path.isdir(cand) else \
        "/home/rohit/sprs-review/runs/20260817T230831Z/council/work"


COUNCIL = os.environ.get("SPRS_COUNCIL") or _council_default()
HERE = os.path.dirname(os.path.abspath(__file__))
PAPER = os.path.dirname(HERE)

SEL = json.load(open(os.path.join(COUNCIL, "SELECTION_RULE.json"), encoding="utf-8"))
rates = SEL["s2_membership_rates"]["algorithm"]

# family metadata (design fact, from the released compiler; not a measurement)
FAMILY = {
    "HEFT": "list scheduling", "CPOP": "list scheduling", "DFSseed": "list scheduling",
    "Lukes": "tree DP", "Frederickson": "tree DP",
    "RecBisect": "graph partition", "DKway": "graph partition",
    "ParSub": "hierarchical", "ClHEFT": "hierarchical", "SubPack": "hierarchical",
    "DSC": "clustering", "CPFD": "clustering", "Chr\\'etienne": "clustering",
    "MLfm": "multilevel", "Centroid": "geometric",
    "Spine": "structural", "LvlHLF": "structural",
    "ExactBB": "exact/B\\&B",
}
ALIAS = {"2h_Chretienne": "Chr\\'etienne"}
PORTFOLIO = {"Lukes", "Frederickson", "ParSub", "DSC"}

rows = {}
for key, rate in rates.items():
    name = ALIAS.get(key, key.split("_", 1)[1])
    if name not in FAMILY:
        sys.exit(f"unknown algorithm {name!r}")
    rows[name] = rate

if len(rows) != 18:
    sys.exit(f"expected 18 S2 algorithms, got {len(rows)}")

order = ["tree DP", "hierarchical", "graph partition", "clustering",
         "multilevel", "geometric", "structural", "list scheduling", "exact/B&B"]
def famkey(n):
    f = FAMILY[n].replace("\\&", "&")
    return (order.index(f), n)

out = [
    "% GENERATED by scripts/gen_catalogue.py -- do not edit by hand.",
    "% source : council/work/SELECTION_RULE.json (s2_membership_rates.algorithm)",
    "% metric : share of HW-validated instances on which the algorithm is a member",
    "%          of the champion equivalence class C_i (tie-invariant; NOT a win count)",
    "% order  : by family, then by name -- deliberately not by membership",
    "\\begin{tabular}{@{}llr@{}}",
    "\\toprule",
    "Algorithm & Family & In champion class \\\\",
    "\\midrule",
]
for name in sorted(rows, key=famkey):
    star = "$^{\\star}$" if name in PORTFOLIO else ""
    out.append(f"\\sv{{{name}}}{star} & {FAMILY[name]} & {100*rows[name]:.1f}\\% \\\\")
out += ["\\bottomrule", "\\end{tabular}"]

dst = os.path.join(PAPER, "tables", "catalogue.tex")
open(dst, "w", encoding="utf-8").write("\n".join(out) + "\n")
print("wrote", dst)
