#!/usr/bin/env python3
r"""
verify_tables.py -- prove every generated .tex in this tree is what its
generator actually produces, AND that a generator exists at all.

Why this exists (part 1).  Three generated files in this paper had been edited
BY HAND after generation, while still carrying the "% GENERATED - do not edit
by hand" banner:

  tables/perinstance_full.tex  assignment/mapping columns deleted (council T15)
  tables/catalogue.tex         replaced with champion-class membership (T15)
  tables/selection.tex         emitted by a script outside the release entirely

Nothing detected that.  `make tables` therefore silently reinstated two refuted
claims, and `make` after it produced a DIFFERENT paper from the one shipped.

Why this exists (part 2) -- THE VACUITY DEFECT.  The first version of this
script copied the paper to a scratch directory, ran `make tables` there, and
diffed each committed file against the copy.  For a file that NO generator
rewrites, the "regenerated" side of that diff is a byte-identical copy of the
committed file, so it always matched -- and the file was still counted in the
banner line "all 28 generated .tex files reproduce from their generators".
data/claim_macros.tex was in exactly that position: 28 generated .tex files
exist, `make tables` rewrote 27, and the one it never touched was the one the
guard could not fail on.  That is how \OrderLRDiff shipped printing "ten" when
the value a referee recomputes from released source in ~40 lines of Python is
twelve.

What is checked now.  MANIFEST below names every generated file and the script
that writes it.  A file cannot pass by being compared against itself:

  C1  every generator named in MANIFEST exists under scripts/ and is invoked by
      the `tables` target of the Makefile;
  C2  every MANIFEST file is REWRITTEN by `make tables` in the scratch copy --
      checked by back-dating every .tex there first and requiring a fresh
      mtime.  A file with no generator fails here;
  C3  every MANIFEST file's committed bytes equal the regenerated bytes
      (provenance headers excluded);
  C4  coverage, so a new file cannot slip in unchecked: every .tex directly
      under tables/ and data/ must appear in MANIFEST, and so must every .tex
      anywhere under figures/ that declares itself GENERATED.  Hand-authored
      figure sources (no GENERATED banner) are listed, not failed.

Usage:  python3 scripts/verify_tables.py [--keep]
Exit 0 = every generated file has a generator and reproduces from it.

NOTE ON COPYING.  The scratch copy is made with symlinks preserved.  Copying
this tree with `cp -rL` dereferences the SPRS_ROOT data symlink and makes
generators fail to reproduce for reasons that have nothing to do with the
paper; use `cp -a`, or this script.
"""
import argparse
import difflib
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time

HERE = os.path.dirname(os.path.abspath(__file__))
PAPER = os.path.dirname(HERE)
ROOT = os.environ.get("SPRS_ROOT") or os.path.abspath(os.path.join(PAPER, ".."))

# Every generated .tex in this tree and the script that writes it.  Where two
# generators write the same file the LAST writer in the Makefile's `tables`
# target is named (see the ORDER MATTERS comment there).
MANIFEST = {
    "tables/_style.tex":            "gen_tablestyle.py",
    "tables/budget.tex":            "gen_tables.py",
    "tables/catalogue_s2.tex":      "gen_tables.py",
    "tables/catalogue_s3.tex":      "gen_tables.py",
    "tables/dedup.tex":             "gen_tables.py",
    "tables/invariance.tex":        "gen_tables.py",
    "tables/perinstance.tex":       "gen_tables.py",
    "tables/suite.tex":             "gen_tables.py",
    "tables/nginflection.tex":      "gen_cost_tables.py",
    "tables/omegaratio.tex":        "gen_cost_tables.py",
    "tables/perinstance_full.tex":  "gen_tournament.py",
    "tables/selbias.tex":           "gen_tournament.py",
    "tables/winners_family.tex":    "gen_tournament.py",
    "tables/radix.tex":             "gen_resource.py",
    "tables/resource.tex":          "gen_resource.py",
    "tables/coverage.tex":          "gen_coverage.py",
    "tables/walltime.tex":          "gen_coverage.py",
    "tables/catalogue.tex":         "gen_catalogue.py",
    "tables/selection.tex":         "gen_selection.py",
    "tables/ksweep.tex":            "gen_ksweep.py",
    "tables/invariants.tex":        "gen_assumptions.py",
    "tables/obligations.tex":       "gen_assumptions.py",
    "data/tournament_macros.tex":   "gen_tournament.py",
    "data/resource_macros.tex":     "gen_resource.py",
    "data/coverage_macros.tex":     "gen_coverage.py",
    "data/campaign_macros.tex":     "gen_campaign_macros.py",
    "data/results_macros.tex":      "gen_results_macros.py",
    "data/fabric_macros.tex":       "gen_fabric_macros.py",
    "data/wround_macros.tex":       "gen_wround_macros.py",
    "data/claim_macros.tex":        "gen_claim_macros.py",
    "figures/ng_inflection.tex":    "gen_figures.py",
    "figures/omega_by_instance.tex": "gen_figures.py",
}

# Lines that legitimately differ run-to-run: the generation date and the
# absolute path of the input dataset.  Nothing else may differ.
VOLATILE = re.compile(
    r"^%\s*(date|Generated|source|Inputs)\b|^%\s+/|^%\s+<P1>|^%\s{6,}\S+\.csv")

BACKDATE = time.mktime((2000, 1, 1, 0, 0, 0, 0, 1, -1))
# Anchored on the literal banner, case-sensitively. With re.I this matched the
# ordinary lower-case word "generated" inside a provenance comment -- e.g.
# figures/variants/f08_coverage/a.tex ("the generated cell counts") -- and aborted
# C4 on hand-authored files, which masked every later stage of the check.
GEN_BANNER = re.compile(r"GENERATED.{0,80}?do not edit by hand", re.S | re.I)


def body(path):
    with open(path, encoding="utf-8", errors="replace") as f:
        return [ln for ln in f if not VOLATILE.match(ln)]


def declares_generated(path):
    try:
        with open(path, encoding="utf-8", errors="replace") as f:
            head = [next(f, "") for _ in range(5)]
    except OSError:
        return False
    return any(GEN_BANNER.search(ln) for ln in head if ln.startswith("%"))


def all_tex(base):
    """Every .tex under tables/ and data/ (top level) and figures/ (recursive)."""
    found = []
    for sub in ("tables", "data"):
        d = os.path.join(base, sub)
        if os.path.isdir(d):
            found += [f"{sub}/{fn}" for fn in sorted(os.listdir(d))
                      if fn.endswith(".tex")]
    fd = os.path.join(base, "figures")
    for dirpath, _, files in os.walk(fd):
        for fn in sorted(files):
            if fn.endswith(".tex"):
                found.append(os.path.relpath(os.path.join(dirpath, fn), base))
    return sorted(found)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--keep", action="store_true")
    a = ap.parse_args()
    problems = []

    # ---- C1: every named generator exists and `make tables` runs it --------
    mk = os.path.join(PAPER, "Makefile")
    with open(mk, encoding="utf-8") as fh:
        mk_txt = fh.read()
    m = re.search(r"^tables:\n((?:\t.*\n)+)", mk_txt, re.M)
    tables_recipe = m.group(1) if m else ""
    if not tables_recipe:
        problems.append("Makefile has no `tables:` recipe -- nothing can be "
                        "regenerated, so nothing below is meaningful")
    for f, gen in sorted(MANIFEST.items()):
        if not os.path.isfile(os.path.join(HERE, gen)):
            problems.append(f"{f}: its generator scripts/{gen} does not exist")
        elif gen not in tables_recipe:
            problems.append(f"{f}: scripts/{gen} exists but the Makefile's "
                            "`tables` target never runs it, so `make tables` "
                            "does not regenerate this file")

    # ---- C4: coverage -- nothing generated may sit outside MANIFEST --------
    hand = []
    for rel in all_tex(PAPER):
        if rel in MANIFEST:
            continue
        p = os.path.join(PAPER, rel)
        if rel.startswith(("tables/", "data/")):
            problems.append(
                f"{rel}: present under {rel.split('/')[0]}/ but absent from "
                "MANIFEST.  Every file in these two directories is generated; "
                "add it to MANIFEST together with the script that writes it, "
                "and make sure `make tables` runs that script.")
        elif declares_generated(p):
            problems.append(
                f"{rel}: declares itself GENERATED but is absent from MANIFEST, "
                "so nothing checks that a generator produces it.  Add it to "
                "MANIFEST, or remove the banner if it is hand-authored.")
        else:
            hand.append(rel)
    for rel in sorted(MANIFEST):
        if not os.path.exists(os.path.join(PAPER, rel)):
            problems.append(f"{rel}: in MANIFEST but not present in the tree")

    if problems:
        for p in problems:
            print("FAIL: " + p)
        print(f"\nFAIL: {len(problems)} structural problem(s); the "
              "regeneration check was not run.")
        return 1

    # ---- scratch copy, back-dated, regenerated -----------------------------
    tmp = tempfile.mkdtemp(prefix="sprs_verify_tables_",
                           dir=os.environ.get("SPRS_SCRATCH") or None)
    work = os.path.join(tmp, "paper")
    # symlinks=True: never dereference: `cp -rL` on this tree breaks SPRS_ROOT.
    shutil.copytree(PAPER, work, symlinks=True,
                    ignore=shutil.ignore_patterns("__pycache__", "*.pdf",
                                                  "*.aux", "*.log", "*.out",
                                                  "*.bbl", "*.blg", "*.bak*"))
    for rel in all_tex(work):
        os.utime(os.path.join(work, rel), (BACKDATE, BACKDATE))

    env = dict(os.environ)
    env["SPRS_ROOT"] = ROOT          # the copy is outside the repo
    r = subprocess.run(["make", "tables"], cwd=work, env=env,
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if r.returncode != 0:
        sys.stdout.write(r.stdout.decode(errors="replace"))
        print("FAIL: `make tables` itself failed in the scratch copy")
        if not a.keep:
            shutil.rmtree(tmp, ignore_errors=True)
        return 2

    # ---- C2: rewritten?   C3: identical? ----------------------------------
    not_written, differ = [], []
    for rel in sorted(MANIFEST):
        regen = os.path.join(work, rel)
        if not os.path.exists(regen):
            not_written.append((rel, "the generator deleted or never wrote it"))
            continue
        if os.stat(regen).st_mtime <= BACKDATE:
            not_written.append((rel, "no generator rewrote it"))
            continue
        if body(os.path.join(PAPER, rel)) != body(regen):
            differ.append(rel)

    rc = 0
    if not_written:
        print("=== files that `make tables` does NOT regenerate ===")
        for rel, why in not_written:
            print(f"  {rel}: {why} (MANIFEST names scripts/{MANIFEST[rel]})")
        print("  A file no generator rewrites cannot be verified: the earlier")
        print("  version of this script compared it against its own copy and")
        print("  passed. It is now a failure.")
        rc = 1
    for f in differ:
        print(f"\n=== {f} : committed file is NOT what the generator produces ===")
        sys.stdout.writelines(difflib.unified_diff(
            body(os.path.join(PAPER, f)), body(os.path.join(work, f)),
            "committed", "regenerated", n=1))
    if differ:
        rc = 1

    if rc:
        print(f"\nFAIL: {len(not_written)} of {len(MANIFEST)} generated file(s) "
              f"are not regenerated, {len(differ)} do not reproduce")
    else:
        print(f"OK: all {len(MANIFEST)} generated .tex files were rewritten by "
              f"`make tables` and reproduce byte-for-byte from their generators")
        if hand:
            print(f"    ({len(hand)} hand-authored .tex not claiming to be "
                  f"generated, not checked: {', '.join(hand)})")
    if a.keep:
        print(f"  scratch copy at {work}")
    else:
        shutil.rmtree(tmp, ignore_errors=True)
    return rc


if __name__ == "__main__":
    sys.exit(main())
